name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  # This will build the Java application
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v2
      with: 
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean package
          
    - uses: actions/upload-artifact@v4
      with:
        name: verademo.war
        path: target/verademo.war
