name: JorCIv2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.8.2 # Example of pinning to a specific version

      - name: Set up JDK 8
        uses: actions/setup-java@v3.0.2 # Example of pinning to a specific version
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Cache Maven Packages
        uses: actions/cache@v3.0.3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn -B clean package # '-B' for batch mode (non-interactive)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: verademo.war
          path: target/verademo.war
